services:
  client:
    image: node:lts-alpine
    working_dir: /app
    ports:
      - "8080:5173"
    volumes:
      - ./Spootify-client:/app
      -  /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
  server:
    image: maven:latest
    ports:
      - "8081:8081"
    volumes:
      - ./Server:/app
    working_dir: /app
    command: mvn spring-boot:run -X
  database:
    image: mysql:latest
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spootifydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - spootifydb:/var/lib/mysql

volumes:
  spootifydb:
  


