services:
  client:
    profiles:
      - prod
    build: Spootify-client/.
    working_dir: /app
    ports:
      - "8080:5173"
    volumes:
      - ./Spootify-client:/app
      - /app/node_modules
    command: sh -c "npm run dev -- --host 0.0.0.0"
    depends_on:
      - server
  server:
    profiles:
      - prod
    build: Server/.
    ports:
      - "8081:8081"
    volumes:
      - ./Server:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/spootifydb
    command: sh -c "mvn spring-boot:run -X"
    depends_on:
      - database
  database:
    profiles:
      - prod
      - test
    image: mysql:latest
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spootifydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - spootifydb:/var/lib/mysql


  server-test:
    build: Server/.
    profiles:
      - test
    ports:
      - "8081:8081"
    volumes:
      - ./Server:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/spootifydb
    command: mvn verify
    depends_on:
      - database

volumes:
  spootifydb:


# Es recomendable tener otros servicios para el entorno de pruebas
  


