name: Run Test Containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run test containers
      run: |
        docker compose --profile=test up --build --abort-on-container-exit --exit-code-from server-test

    - name: Upload the reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: Server/target/site

  generate-documentation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run documentation container
      run: |
        docker compose --profile=docs up --build --abort-on-container-exit --exit-code-from server-docs

    - name: Copy site doxygen output to docs folder
      run: |
        mkdir -p docs
        rm -rf docs/site
        mkdir -p docs/site
        cp -r target/site/* docs/site/
        cp -r target/reports/* docs/site/reports/
        rm -rf docs/doxygen
        mkdir -p docs/doxygen
        cp -r target/doxygen/html/* docs/doxygen/
    
    - name: Commit and push docs
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add -f docs
        git commit -m "Update Maven site [CI skip]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
