name: Run Test Containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run test containers
      run: |
        docker compose --profile=test up --build --abort-on-container-exit --exit-code-from server-test

    - name: Upload the reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: Server/target/site

  generate-documentation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run documentation container
      run: |
        docker compose --profile=docs up --build --abort-on-container-exit --exit-code-from server-docs

    - name: Copy site doxygen output to docs folder
      run: |
        ls
        mkdir -p docs
        cp -r Server/target/doxygen/html/* docs/
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
