name: Run Test Containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run test containers
      run: |
        docker compose --profile=test up --build --abort-on-container-exit --exit-code-from server-test

    - name: Upload the reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: Server/target/site

  generate-documentation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run documentation container
      run: |
        docker compose --profile=docs up --build --abort-on-container-exit --exit-code-from server-docs

    - name: Upload pages
      uses: actions/upload-pages-artifact@v3
      id: deployment
      with:
        path: Server/target/doxygen/html

    - name: Deploy pages
      id: deployment
      uses: actions/deploy-pages@v3
